# Generated by Django 2.2.4 on 2020-10-24 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Type your username here', max_length=200)),
                ('email', models.EmailField(help_text='Type your email here', max_length=254)),
                ('password', models.CharField(help_text='Type your password here', max_length=200)),
                ('salt', models.CharField(default='', help_text='Salt for password', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text="It is text describing user's problem here")),
                ('well_being', models.IntegerField(help_text='It is numeric representation of well-being')),
                ('food', models.IntegerField(help_text='It is numeric representation of food')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='This is date whenpost was added')),
                ('icon', models.CharField(help_text='This is name of icon file', max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.User')),
            ],
        ),
    ]
