# Generated by Django 2.2.6 on 2019-10-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20191012_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
