# Generated by Django 2.2.6 on 2019-10-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciekawostki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczbaporzadkowa', models.CharField(max_length=200)),
                ('ciekawostka', models.TextField()),
            ],
        ),
    ]
