# Generated by Django 2.2.6 on 2019-10-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_ciekawostki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciekawostki',
            name='ciekawostka',
            field=models.CharField(max_length=2000),
        ),
    ]
