# Generated by Django 2.2.6 on 2019-10-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20191015_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciekawostki',
            name='tresc',
            field=models.TextField(default=''),
        ),
    ]
