# Generated by Django 2.2.6 on 2019-10-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20191015_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciekawostki',
            name='id',
        ),
        migrations.AlterField(
            model_name='ciekawostki',
            name='liczbaporzadkowa',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
