# Generated by Django 2.2.6 on 2019-10-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20191019_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciekawostki',
            new_name='Curiosity',
        ),
        migrations.RenameField(
            model_name='curiosity',
            old_name='liczbaporzadkowa',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='curiosity',
            old_name='tresc',
            new_name='text',
        ),
    ]
