# Generated by Django 2.2.6 on 2019-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_auto_20191019_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOfUser', models.IntegerField(help_text='Id of user which', max_length=200)),
                ('date', models.DateField(help_text='Date of adding update')),
                ('value', models.IntegerField(help_text='Value of update', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOfUser', models.IntegerField(help_text='Id of user which', max_length=200)),
                ('date', models.DateField(help_text='Date of adding update')),
                ('value', models.IntegerField(help_text='Value of update', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Type your username here', max_length=200)),
                ('email', models.EmailField(help_text='Type your email here', max_length=254)),
                ('password', models.CharField(help_text='Type your password here', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOfUser', models.IntegerField(help_text='Id of user which', max_length=200)),
                ('date', models.DateField(help_text='Date of adding update')),
                ('value', models.IntegerField(help_text='Value of update', max_length=1000)),
            ],
        ),
    ]
