# Generated by Django 2.2.6 on 2019-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_auto_20191022_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas',
            name='idOfUser',
            field=models.IntegerField(help_text='Id of user which'),
        ),
        migrations.AlterField(
            model_name='power',
            name='idOfUser',
            field=models.IntegerField(help_text='Id of user which'),
        ),
        migrations.AlterField(
            model_name='water',
            name='idOfUser',
            field=models.IntegerField(help_text='Id of user which'),
        ),
    ]
