# Generated by Django 2.2.16 on 2020-09-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_user_howmanypeople'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curiosity',
        ),
        migrations.DeleteModel(
            name='Gas',
        ),
        migrations.DeleteModel(
            name='Power',
        ),
        migrations.DeleteModel(
            name='Water',
        ),
        migrations.RemoveField(
            model_name='user',
            name='howManyPeople',
        ),
    ]
