# Generated by Django 2.2.16 on 2020-10-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_auto_20200916_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Type your username here', max_length=200)),
                ('email', models.EmailField(help_text='Type your email here', max_length=254)),
                ('password', models.CharField(help_text='Type your password here', max_length=200)),
                ('salt', models.CharField(default='', help_text='Salt for password', max_length=200)),
            ],
        ),
    ]
