# Generated by Django 2.2.16 on 2020-10-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_auto_20201011_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
